# Generated by Django 3.0.4 on 2021-08-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loginmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=200)),
                #('profilepic', models.CharField(max_length=200)),
                ('profilepic', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'signup',
            },
        ),
    ]
